version: '3.8'

services:
  db-prod:
    image: mysql:8.0
    container_name: mysql-club-prod # Nombre único para PROD
    restart: always
    environment:
      MYSQL_DATABASE: bd_adm_club # (O el nombre que elijas para PROD)
      MYSQL_ROOT_PASSWORD: Mysql.mysql
    ports:
      - "3306:3306" # <-- PROD se queda con el puerto estándar 3306 hacia el exterior
    volumes:
      - mysql_prod_data:/var/lib/mysql # Volumen único para PROD

  mi-club-app-prod:
    image: estebanjpc/mi-club:prod # Tag de producción
    container_name: app-club-prod
    restart: always
    ports:
      - "80:80" # Producción sale por el puerto web estándar
    depends_on:
      - db-prod
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-prod:3306/bd_adm_club_prod?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Mysql.mysql

volumes:
  mysql_prod_data: # Volumen separado para que PROD y DESA no mezclen datos