  GNU nano 6.2                                                                                                                   docker-compose.yml                                                                                                                            
services:
  db-desa:
    image: mysql:8.0
    container_name: mysql-club-desa
    restart: always
    environment:
      MYSQL_DATABASE: bd_adm_club
      MYSQL_ROOT_PASSWORD: Mysql.mysql
    ports:
      - "3307:3306" 
    volumes:
      - mysql_desa_data:/var/lib/mysql

  mi-club-desa:
    image: estebanjpc/mi-club:desa
    ports:
      - "8080:80"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-desa:3306/bd_adm_club?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Mysql.mysql
    restart: always

# --- ESTO ES LO QUE DEBES AGREGAR AL FINAL ---
volumes:
  mysql_desa_data: