version: '3.8'

services:
  db-desa:
    image: mysql:8.0
    container_name: mysql-club-desa
    restart: always
    environment:
      MYSQL_DATABASE: bd_adm_club
      MYSQL_ROOT_PASSWORD: Mysql.mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql_desa_data:/var/lib/mysql

  mi-club-desa:
    image: estebanjpc/mi-club:desa
    container_name: app-club-desa
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db-desa
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-desa:3306/bd_adm_club?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Santiago
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Mysql.mysql
      - SPRING_JPA_DDL_AUTO=validate
      - SERVER_PORT=80
      # URL pública DESA (ajusta si usas subdominio o dominio)
      - APP_PUBLIC_URL=http://45.7.229.27:8080
      # Correo SMTP IRCD
      - MAIL_FROM=test@ircd.cl
      - SPRING_MAIL_HOST=mail.ircd.cl
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=test@ircd.cl
      - SPRING_MAIL_PASSWORD=tu_password_ircd
      - KHIPU_WEBHOOK_VERIFY_SIGNATURE=true
      - ADMIN_SOPORTE_ENABLED=false
      - NOTIFICATIONS_SCHEDULER_ENABLED=true

volumes:
  mysql_desa_data:
